home_app/urls.py
from django.urls import path
from home_app import views

app_name = 'home_app'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('feed/', views.FeedView.as_view(), name='feed'),
    path('search/', views.search, name='search'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='detail_post'),
]

personal_web/urls.py
from django.contrib import admin
from django.urls import path, include
from home_app import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls'), name='enter'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/models.py
from django.db import models

# Create your models here.
class PostDetail(models.Model):
    post_title = models.CharField(max_length=256)
    slug = models.SlugField(null=True, unique=True)
    post_id = models.PositiveIntegerField()
    post_auth = models.CharField(max_length=50, default='')
    auth_link = models.URLField(null=True)
    github_link = models.URLField(null=True, blank=True)
    other_link = models.URLField(null=True, blank=True)
    other_link_desc = models.CharField(max_length=256, null=True, blank=True)
    post_desc = models.TextField()
    creation_date = models.DateField()
    post_video = models.URLField(null=True, blank=True)
    post_image = models.ImageField(null=True, blank=True, upload_to='pic')

    def __str__(self):
        return self.post_title

home_app/views.py
from django.shortcuts import render
from .models import PostDetail
from django.views.generic import TemplateView, ListView, DetailView


# Create your views here.
class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = PostDetail.objects.get(post_id=8)
        return context

class FeedView(ListView):
    context_object_name = 'posts'
    model = PostDetail
    template_name = 'feed.html'

    paginate_by = 3

    def get_queryset(self):
        return PostDetail.objects.filter(post_id__gte=1).order_by('-post_id')


class PostDetailView(DetailView):
    context_object_name = 'post'
    model = PostDetail
    template_name = 'detail_post.html'

def search(request):
    query = request.GET['query']
    allpost = PostDetail.objects.filter(post_title__icontains=query)
    return render(request, 'searched.html', {'allpost':allpost})

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  {% block head_block %}
  {% endblock head_block %}


  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% block title_block %}{% endblock title_block %}

</head>

<body style="background-color: rgb(37, 37, 37);">
  <header>
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark" style="background-color: rgb(0, 0, 0);">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home_app:home' %}">🅸🆂</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item ">
              <a class="nav-link active text-light" href="{% url 'home_app:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active text-light" href="{% url 'home_app:feed' %}">Blog</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active text-light" href="https://github.com/ishaansharma7" target="_blank">GitHub</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle active text-light" href="#" id="navbarDropdown" role="button"
                data-bs-toggle="dropdown" aria-expanded="false">
                FollowMe
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="https://www.instagram.com/ishaansharma711/" target="_blank"><img src="{% static 'base/navbar/instalogo1.png' %}" alt=""> Instagram</a></li>
                <li><a class="dropdown-item" href="https://www.youtube.com/channel/UCLHCqt98yc2vWlU_iZtdAWA" target="_blank"><img src="{% static 'base/navbar/youtube1.png' %}" alt=""> YouTube</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="https://www.linkedin.com/in/ishaan-sharma-245b051a1/"><img src="{% static 'base/navbar/linkedin.png' %}" alt=""> Linkedin</a></li>
              </ul>
            </li>

          </ul>
          <form class="d-flex" method="GET" action="{% url 'home_app:search' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
            <button class="btn btn-outline-light" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

  {% block body_block %}
  {% endblock body_block %}

    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#" class="text-light">UP</a>
        </p>
        <p class="mb-1 text-light">Ishaan Sharma &copy;</p>
        <p class="mb-0 text-light">PVT.</p>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"></script>
</body>

</html>

templates/detail_post.html
{% extends 'base.html' %}
{% load static %}
{% block head_block %}
<title>Feed</title>
<link rel="stylesheet" href="{% static 'feed/feed.css' %}">
{% endblock head_block %}


{% block body_block %}
<div class="container mt-5">
    <div class="row text-light">
        <div class="col-md-8 mt-5">

                <article class="blog-post">
                    <h2 class="blog-post-title text-warning">{{post.post_title}} | post #{{post.post_id}}</h2>
                    <p class="blog-post-meta">{{post.creation_date}} by <a href="{{post.auth_link}}" target="_blank">{{post.post_auth}}</a></p>
                    {% if post.github_link %}<p>Source Code: <a href="{{post.github_link}}" target="_blank">GitHub Link</a></p>{% endif %}


                    <p>{{post.post_desc}}</p>
                    {% if post.post_video %}
                    <iframe width="480" height="270" src="{{post.post_video}}" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>
                    </iframe>
                    {% endif %}

                    {% if post.post_image %}
                    <img class="dbimg" src={{post.post_image.url}}>
                    {% endif %}

                    <hr>
                </article><!-- /.blog-post -->



            <nav class="blog-pagination" aria-label="Pagination">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-warning" href="?page={{ page_obj.previous_page_number }}">Older</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-warning" href="?page={{ page_obj.next_page_number }}">Newer</a>
            {% endif %}
            </nav>

        </div>

        <div class="col-md-4 mt-5">
            <div class="p-4 mb-3 bg-light rounded text-dark">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">Hi I am Ishaan, this is my blog/feed page. This website is created using django framework.</p>
            </div>

            <div class="p-4">
                <h4 class="font-italic text-warning">Other Links</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="https://www.youtube.com/watch?v=JxzZxdht-XY&t=3057s" target="_blank">Django Tutorial In Hindi</a></li>
                    <li><a href="https://www.youtube.com/watch?v=_uQrJ0TkZlc&t=1592s" target="_blank">Python for Beginners [Full Course]</a></li>
                    <li><a href="https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc" target="_blank">Python OOP: Classes and Instances</a></li>
                    <li><a href="https://www.youtube.com/watch?v=vmEHCJofslg&t=3029s" target="_blank">Python Pandas</a></li>
                    <li><a href="https://www.youtube.com/watch?v=yfoY53QXEnI" target="_blank">CSS Crash Course</a></li>

                </ol>
            </div>

            <div class="p-4">
                <h4 class="font-italic text-warning">FollowMe</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/ishaansharma7" target="_blank">GitHub</a></li>
                    <li><a href="https://www.instagram.com/ishaansharma711/" target="_blank">Instagram</a></li>
                    <li><a href="https://www.youtube.com/channel/UCLHCqt98yc2vWlU_iZtdAWA" target="_blank">YouTube</a></li>
                    <li><a href="https://www.linkedin.com/in/ishaan-sharma-245b051a1/" target="_blank">Linkedin</a></li>
                </ol>
            </div>
        </div>

    </div><!-- /.row -->
</div>
{% endblock body_block %}

templates/feed.html
{% extends 'base.html' %}
{% load static %}
{% block head_block %}
<title>Feed</title>
<link rel="stylesheet" href="{% static 'feed/feed.css' %}">
{% endblock head_block %}


{% block body_block %}
<div class="container mt-5">
    <div class="row text-light">
        <div class="col-md-8 mt-5">
            {% for post in posts %}
                <article class="blog-post">
                    <h2 class="blog-post-title" style="color: rgb(255, 255, 255);"><strong>{{post.post_title}} | post #{{post.post_id}}</strong></h2>
                    <p class="blog-post-meta">{{post.creation_date}} by <a href="{{post.auth_link}}" target="_blank">{{post.post_auth}}</a></p>
                    {% if post.github_link %}<p>Source Code: <a href="{{post.github_link}}" target="_blank">GitHub Link</a></p>{% endif %}
                    {% if post.other_link %}<p>Link: <a href="{{post.other_link}}" target="_blank">{{post.other_link_desc}}</a></p>{% endif %}


                    <p>{{post.post_desc | safe}}</p>
                    {% if post.post_video %}
                    <iframe width="480" height="270" src="{{post.post_video}}" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>
                    </iframe>
                    {% endif %}

                    {% if post.post_image %}
                    <img class="dbimg" src={{post.post_image.url}}>
                    {% endif %}

                    <hr>
                </article><!-- /.blog-post -->
            {% endfor %}


            <nav class="blog-pagination" aria-label="Pagination">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-light" href="?page={{ page_obj.previous_page_number }}">Newer</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-light" href="?page={{ page_obj.next_page_number }}">Older</a>
            {% endif %}
            </nav>

        </div>

        <div class="col-md-4 mt-5">
            <div class="p-4 mb-3 bg-light rounded text-dark">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">Hi I am Ishaan, this is my blog/feed page. This website is created using django framework.</p>
            </div>

            <div class="p-4">
                <h4 class="font-italic">Other Links</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="https://www.youtube.com/watch?v=JxzZxdht-XY&t=3057s" target="_blank">Django Tutorial In Hindi</a></li>
                    <li><a href="https://www.youtube.com/watch?v=_uQrJ0TkZlc&t=1592s" target="_blank">Python for Beginners [Full Course]</a></li>
                    <li><a href="https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc" target="_blank">Python OOP: Classes and Instances</a></li>
                    <li><a href="https://www.youtube.com/watch?v=vmEHCJofslg&t=3029s" target="_blank">Python Pandas</a></li>
                    <li><a href="https://www.youtube.com/watch?v=yfoY53QXEnI" target="_blank">CSS Crash Course</a></li>

                </ol>
            </div>

            <div class="p-4">
                <h4 class="font-italic">FollowMe</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/ishaansharma7" target="_blank">GitHub</a></li>
                    <li><a href="https://www.instagram.com/ishaansharma711/" target="_blank">Instagram</a></li>
                    <li><a href="https://www.youtube.com/channel/UCLHCqt98yc2vWlU_iZtdAWA" target="_blank">YouTube</a></li>
                    <li><a href="https://www.linkedin.com/in/ishaan-sharma-245b051a1/" target="_blank">Linkedin</a></li>
                </ol>
            </div>
        </div>

    </div><!-- /.row -->
</div>
{% endblock body_block %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'home/home.css' %}">
<title>Home</title>
{% endblock head_block %}

{% block body_block %}

<div id="carouselExampleCaptions" class="carousel slide mt-5" data-bs-ride="carousel">
  <ol class="carousel-indicators">
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
    <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'home/c1.png' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-flex h-100 align-items-center justify-content-center">
        <h1>Python Tutorials</h1>

      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'home/c2.png' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-flex h-100 align-items-center justify-content-center">
        <h1>Python Projects</h1>

      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'home/c3.png' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-flex h-100 align-items-center justify-content-center">
        <h1>Get Source Code</mark></h1>

      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </a>
</div>

<div class="container mt-5">

  <div class="row">
    <div class="col-md-4 mb-3">

      <div class="face-name">
        <img src="{% static 'home/face.jpg' %}" alt="">
      </div>
      <div class="mt-3" style="text-align: center;">
        <h2 class="text-light">𝐈𝐬𝐡𝐚𝐚𝐧 𝐒𝐡𝐚𝐫𝐦𝐚</h2>
      </div>


    </div>
    <div class="col-md-8 mb-3 left-holder px-3 pt-4">
      <div class="my-desc">
        <p class="desc-back text-light">Hi, I am Ishaan Sharma a computer science student. I run a YouTube channel on python
          language and related
          technologies, created and published an indie game on play store, have participated and won in many
          hackathons. My area of expertise- <br> 1) Front End Web Development (HTML, CSS, Bootstrap, JavaScript) <br> 2)
          Back
          End Web Development (Django) <br> 3) Python and Automation using many popular packages and modules.
        </p>
      </div>
    </div>
  </div>

   <h1 class="mt-5 text-light" style="text-align: center;">Featured Post</h1>
  {% comment %} <div class="iframe-container">
    <iframe width="480" height="270" src="https://www.youtube.com/embed/mxf0yPeiihQ" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
      allowfullscreen></iframe> {% endcomment %}
  </div> 
  <div class="container mt-5">
    <div class="row text-light">
        <div class="col-md-8 mt-5">
            
                <article class="blog-post">
                    <h2 class="blog-post-title text-light">{{post.post_title}} | post #{{post.post_id}}</h2>
                    <p class="blog-post-meta">{{post.creation_date}} by <a href="{{post.auth_link}}" target="_blank">{{post.post_auth}}</a></p>
                    {% if post.github_link %}<p>Source Code: <a href="{{post.github_link}}" target="_blank">GitHub Link</a></p>{% endif %}
                    {% if post.other_link %}<p>Link: <a href="{{post.other_link}}" target="_blank">{{post.other_link_desc}}</a></p>{% endif %}

                    <p>{{post.post_desc}}</p>
                    {% if post.post_video %}
                    <iframe width="480" height="270" src="{{post.post_video}}" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>
                    </iframe>
                    {% endif %}
                    
                    {% if post.post_image %}
                    <img class="dbimg" src={{post.post_image.url}}>
                    {% endif %}
                    
                    <hr>
                </article><!-- /.blog-post -->
            
            

            <nav class="blog-pagination" aria-label="Pagination">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-warning" href="?page={{ page_obj.previous_page_number }}">Older</a>
            {% endif %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-warning" href="?page={{ page_obj.next_page_number }}">Newer</a>
            {% endif %}
            </nav>
            
        </div>

        <div class="col-md-4 mt-5">
            <div class="p-4 mb-3 bg-light rounded text-dark">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">Hi I am Ishaan, this is my blog/feed page. This website is created using django framework.</p>
            </div>

            <div class="p-4">
                <h4 class="font-italic text-light">Other Links</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="https://www.youtube.com/watch?v=JxzZxdht-XY&t=3057s" target="_blank">Django Tutorial In Hindi</a></li>
                    <li><a href="https://www.youtube.com/watch?v=_uQrJ0TkZlc&t=1592s" target="_blank">Python for Beginners [Full Course]</a></li>
                    <li><a href="https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc" target="_blank">Python OOP: Classes and Instances</a></li>
                    <li><a href="https://www.youtube.com/watch?v=vmEHCJofslg&t=3029s" target="_blank">Python Pandas</a></li>
                    <li><a href="https://www.youtube.com/watch?v=yfoY53QXEnI" target="_blank">CSS Crash Course</a></li>
                    
                </ol>
            </div>

            <div class="p-4">
                <h4 class="font-italic text-light">FollowMe</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/ishaansharma7" target="_blank">GitHub</a></li>
                    <li><a href="https://www.instagram.com/ishaansharma711/" target="_blank">Instagram</a></li>
                    <li><a href="https://www.youtube.com/channel/UCLHCqt98yc2vWlU_iZtdAWA" target="_blank">YouTube</a></li>
                    <li><a href="https://www.linkedin.com/in/ishaan-sharma-245b051a1/" target="_blank">Linkedin</a></li>
                </ol>
            </div>
        </div>

    </div><!-- /.row -->
</div>
  {% endblock body_block %}

templates/searched.html
{% extends 'base.html' %}
{% load static %}
{% block head_block %}
<title>Feed</title>
<link rel="stylesheet" href="{% static 'feed/feed.css' %}">
{% endblock head_block %}


{% block body_block %}
<div class="container mt-5">
    <div class="row text-light">
        <div class="col-md-8 mt-5">
        {% if allpost|length > 0 %}
            {% for post in allpost %}
                <article class="blog-post">
                    <h2 class="blog-post-title text-light">{{post.post_title}} | post #{{post.post_id}}</h2>
                    <p class="blog-post-meta">{{post.creation_date}} by <a href="{{post.auth_link}}" target="_blank">{{post.post_auth}}</a></p>
                    {% if post.github_link %}<p>Source Code: <a href="{{post.github_link}}" target="_blank">GitHub Link</a></p>{% endif %}
                    {% if post.other_link %}<p>Link: <a href="{{post.other_link}}" target="_blank">{{post.other_link_desc}}</a></p>{% endif %}

                    <p>{{post.post_desc}}</p>
                    {% if post.post_video %}
                    <iframe width="480" height="270" src="{{post.post_video}}" frameborder="0"
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>
                    </iframe>
                    {% endif %}
                    
                    {% if post.post_image %}
                    <img class="dbimg" src={{post.post_image.url}}>
                    {% endif %}
                    
                    <hr>
                </article><!-- /.blog-post -->
            {% endfor %}
            {% else %}
            <h2 class="blog-post-title text-light">Sorry No Results 😥</h2>
            {% endif %}
            
            

            
            
        </div>

        <div class="col-md-4 mt-5">
            <div class="p-4 mb-3 bg-light rounded text-dark">
                <h4 class="font-italic">About</h4>
                <p class="mb-0">Hi I am Ishaan, this is my blog/feed page. This website is created using django framework.</p>
            </div>

            <div class="p-4">
                <h4 class="font-italic text-light">Other Links</h4>
                <ol class="list-unstyled mb-0">
                    <li><a href="https://www.youtube.com/watch?v=JxzZxdht-XY&t=3057s" target="_blank">Django Tutorial In Hindi</a></li>
                    <li><a href="https://www.youtube.com/watch?v=_uQrJ0TkZlc&t=1592s" target="_blank">Python for Beginners [Full Course]</a></li>
                    <li><a href="https://www.youtube.com/watch?v=ZDa-Z5JzLYM&list=PL-osiE80TeTsqhIuOqKhwlXsIBIdSeYtc" target="_blank">Python OOP: Classes and Instances</a></li>
                    <li><a href="https://www.youtube.com/watch?v=vmEHCJofslg&t=3029s" target="_blank">Python Pandas</a></li>
                    <li><a href="https://www.youtube.com/watch?v=yfoY53QXEnI" target="_blank">CSS Crash Course</a></li>
                    
                </ol>
            </div>

            <div class="p-4">
                <h4 class="font-italic text-light">FollowMe</h4>
                <ol class="list-unstyled">
                    <li><a href="https://github.com/ishaansharma7" target="_blank">GitHub</a></li>
                    <li><a href="https://www.instagram.com/ishaansharma711/" target="_blank">Instagram</a></li>
                    <li><a href="https://www.youtube.com/channel/UCLHCqt98yc2vWlU_iZtdAWA" target="_blank">YouTube</a></li>
                    <li><a href="https://www.linkedin.com/in/ishaan-sharma-245b051a1/" target="_blank">Linkedin</a></li>
                </ol>
            </div>
        </div>

    </div><!-- /.row -->
</div>
{% endblock body_block %}